# Generated by Django 5.2.6 on 2025-12-20 01:03

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the User model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.name = f"{user.first_name} {user.last_name}"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birthday_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
