# Generated by Django 5.2.6 on 2025-09-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='bar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.bar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='name',
            field=models.CharField(default='Default Drink', max_length=60),
        ),
    ]
