# Generated by Django 5.2.6 on 2025-09-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_drink_bar_drink_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='tags',
        ),
        migrations.AddField(
            model_name='drink',
            name='tags',
            field=models.ManyToManyField(related_name='ratings', to='ratings.tag'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='ratings.bar'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.bar'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.drink'),
        ),
    ]
