# Generated by Django 5.2.6 on 2025-09-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_tags_drink_tags_alter_drink_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='tags',
            field=models.ManyToManyField(related_name='drinks', to='ratings.tag'),
        ),
    ]
