# Generated by Django 5.2.6 on 2025-11-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rating_presentation_rating_rating_taste_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='geoapify_place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
