# Generated by Django 5.2.6 on 2025-11-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_bar_geoapify_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='geoapify_place_id',
            new_name='foursquare_place_id',
        ),
    ]
