# Generated by Django 5.2.6 on 2025-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_rename_geoapify_place_id_bar_foursquare_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='formatted_address',
            field=models.TextField(default=''),
        ),
    ]
